// Params
const SET_NUMBER_OF_EXERCISES = "SET_NUMBER_OF_EXERCISES"
const SET_EXERCISE_TIME = "SET_EXERCISE_TIME"
const SET_REST_TIME = "SET_REST_TIME"
const SET_NUMBER_OF_ROUNDS = "SET_NUMBER_OF_ROUNDS"
const CLEAR_PARAMS = "CLEAR_PARAMS"
const SET_EXERCISES = "SET_EXERCISES"
const SET_EXERCISE_ROUNDS = "SET_EXERCISE_ROUNDS"

// Is Active
const IS_ACTIVE_TRUE = "IS_ACTIVE_TRUE"
const IS_ACTIVE_FALSE = "IS_ACTIVE_FALSE"

export {
    // Params
    SET_NUMBER_OF_EXERCISES,
    SET_EXERCISE_TIME,
    SET_REST_TIME,
    SET_NUMBER_OF_ROUNDS,
    CLEAR_PARAMS,
    SET_EXERCISES,
    SET_EXERCISE_ROUNDS,

    // Is Active
    IS_ACTIVE_TRUE,
    IS_ACTIVE_FALSE,
}