const SET_NUMBER_OF_EXERCISES = "SET_NUMBER_OF_EXERCISES"
const SET_EXERCISE_TIME = "SET_EXERCISE_TIME"
const SET_REST_TIME = "SET_REST_TIME"
const SET_NUMBER_OF_ROUNDS = "SET_NUMBER_OF_ROUNDS"

export {
    SET_NUMBER_OF_EXERCISES,
    SET_EXERCISE_TIME,
    SET_REST_TIME,
    SET_NUMBER_OF_ROUNDS
}